schemaVersion: 2.0.0

fileExistenceTests:
  - name: 'ptvsd for python 2.7'
    path: '/duct-tape/python/lib/python2.7/site-packages/ptvsd/__init__.py'
  - name: 'debugpy for python 2.7'
    path: '/duct-tape/python/lib/python2.7/site-packages/debugpy/__init__.py'
  - name: 'ptvsd for python 3.7'
    path: '/duct-tape/python/lib/python3.7/site-packages/ptvsd/__init__.py'
  - name: 'debugpy for python 3.7'
    path: '/duct-tape/python/lib/python3.7/site-packages/debugpy/__init__.py'
  - name: 'ptvsd for python 3.8'
    path: '/duct-tape/python/lib/python3.8/site-packages/ptvsd/__init__.py'
  - name: 'debugpy for python 3.8'
    path: '/duct-tape/python/lib/python3.8/site-packages/debugpy/__init__.py'
  - name: 'ptvsd for python 3.9'
    path: '/duct-tape/python/lib/python3.9/site-packages/ptvsd/__init__.py'
  - name: 'debugpy for python 3.9'
    path: '/duct-tape/python/lib/python3.9/site-packages/debugpy/__init__.py'
  - name: 'python launcher'
    path: '/duct-tape/python/launcher'
    isExecutableBy: any

commandTests:
  - name: "run with no /dbg should fail"
    command: "sh"
    args: ["/install.sh"]
    expectedError: ["Error: installation requires a volume mount at /dbg"]
    exitCode: 1
  - name: "run with /dbg should install"
    setup: [["mkdir", "/dbg"]]
    command: "sh"
    args: ["/install.sh"]
    expectedOutput: ["Installing runtime debugging support files in /dbg", "Installation complete"]
    exitCode: 0
